# Generated by Django 4.0.5 on 2022-07-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.base')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('user', models.CharField(max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=12, verbose_name='Contraseña')),
            ],
            bases=('api.base',),
        ),
    ]
