# Generated by Django 4.0.5 on 2022-07-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.base')),
                ('articulo', models.CharField(max_length=255, verbose_name='Articulo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            bases=('api.base',),
        ),
    ]
